source "https://rubygems.org"

gemspec

gem "chef_backup"
gem "omnibus-ctl", git: "https://github.com/chef/omnibus-ctl.git", tag: "v0.6.0"
gem 'veil', '~> 0.3.0' # version dependency
gem "toml" # for habitat-land